T1-1. 데이터에서 IQR을 활용해 Fare컬럼의 이상치를 찾고, 이상치 데이터의 여성 수를 구하시오

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/Titanic.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
q1 = df['Fare'].quantile(.25)
q3 = df['Fare'].quantile(.25)
IQR = q3 - q1

In [ ]:
outdata_1 = df[ df['Fare'] < (q1-IQR*1.5)]
outdata_2 = df[ df['Fare'] > (q3+IQR*1.5)]

len(outdata_1), len(outdata_2)

In [ ]:
print( sum(outdata_1['Gender'] == 'female') + sum(outdata_2['Gender'] == 'female'))

T1-2. 주어진 데이터에서 이상치(소수점 나이)를 찾고 올림, 내림, 버림(절사)했을때 3가지 모두 이상치 'age' 평균을 구한 다음 모두 더하여 출력하시오

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/basic1.csv')

In [ ]:
df.head()

In [ ]:
# 소수점 나이 추출/ 올림,내림,버림을 각각 적용했을 때의 평균 구하기/ 3가지 경우의 평균 모두 합

In [ ]:
df = df[ (df['age'] - np.floor(df['age'])) != 0 ] # 원본 age값 - 내림 age값의 계산 결과가 0이 아닌 경우 True 반환
df

In [ ]:
# 올림,내림,버림의 각 평균값
ceil_mean = np.ceil(df['age']).mean()
floor_mean = np.floor(df['age']).mean()
trunc_mean = np.trunc(df['age']).mean()

In [ ]:
print(ceil_mean + floor_mean + trunc_mean)

T1-3. 주어진 데이터에서 결측치가 80%이상 되는 컬럼은(변수는) 삭제하고, 80% 미만인 결측치가 있는 컬럼은 'city'별 중앙값으로 값을 대체하고 'f1'컬럼의 평균값을 출력하세요!

In [ ]:
# 결측치 처리(map 활용)
import pandas as pd
import numpy as np

df = pd.read_csv('/content/basic1.csv')
print(df.shape)
print(df.isna().sum())
df.head()

(100, 8)
id       0
age      0
city     0
f1      31
f2       0
f3      95
f4       0
f5       0
dtype: int64

     id   age city    f1  f2   f3    f4         f5
0  id01   2.0   서울   NaN   0  NaN  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  NaN  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  NaN  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  NaN  INFP  52.667078
4  id05  24.0   서울  85.0   2  NaN  ISFJ  29.269869

In [ ]:
df.isna().sum() / df.shape[0] # 결측치 비율: 결측치 수 / 전체 수
# df.shape[0]:전체 행의 수 반환  df.shape[1]:열

id      0.00
age     0.00
city    0.00
f1      0.31
f2      0.00
f3      0.95
f4      0.00
f5      0.00
dtype: float64

In [ ]:
df = df.drop(columns=['f3'])
df

       id    age city    f1  f2    f4         f5
0    id01    2.0   서울   NaN   0  ENFJ  91.297791
1    id02    9.0   서울  70.0   1  ENFJ  60.339826
2    id03   27.0   서울  61.0   1  ISTJ  17.252986
3    id04   75.0   서울   NaN   2  INFP  52.667078
4    id05   24.0   서울  85.0   2  ISFJ  29.269869
..    ...    ...  ...   ...  ..   ...        ...
95   id96   92.0   경기  53.0   1  ENTJ  52.667078
96   id97  100.0   경기   NaN   0  INFP  67.886373
97   id98   39.0   경기  58.0   2  INFP  98.429899
98   id99    1.0   경기  47.0   0  ESFJ  97.381034
99  id100   47.0   경기  53.0   0  ESFP  33.308999

[100 rows x 7 columns]

In [ ]:
df['city'].value_counts()

city
경기    41
서울    20
대구    20
부산    19
Name: count, dtype: int64

In [ ]:
k_median = df[df['city'] == '경기']['f1'].median() # 'city'열의 값이 '경기'인 행을 필터링하고, 그중에서 'f1'열의 중앙값을 계산
s_median = df[df['city'] == '서울']['f1'].median()
d_median = df[df['city'] == '대구']['f1'].median()
b_median = df[df['city'] == '부산']['f1'].median()

k_median, s_median, d_median, b_median

(58.0, 68.0, 75.0, 62.0)

In [ ]:
df.head()

     id   age city    f1  f2    f4         f5
0  id01   2.0   서울   NaN   0  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  INFP  52.667078
4  id05  24.0   서울  85.0   2  ISFJ  29.269869

In [ ]:
df['f1'] = df['f1'].fillna(df['city'].map({'경기':k_median, '서울':s_median, '대구':d_median, '부산':b_median}))
# map(): pandas에서 시리즈(Series)의 값들을 다른 값으로 매핑(mapping)하거나 변환

# 만약 f1 중앙값으로 대체한다면
# df['f1'] = df['f1'].fillna(df['f1'].median())

In [ ]:
df.head()

     id   age city    f1  f2    f4         f5
0  id01   2.0   서울  68.0   0  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  ISTJ  17.252986
3  id04  75.0   서울  68.0   2  INFP  52.667078
4  id05  24.0   서울  85.0   2  ISFJ  29.269869

In [ ]:
print(df['f1'].mean())

65.52