T1-1. 데이터에서 IQR을 활용해 Fare컬럼의 이상치를 찾고, 이상치 데이터의 여성 수를 구하시오

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/Titanic.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
q1 = df['Fare'].quantile(.25)
q3 = df['Fare'].quantile(.25)
IQR = q3 - q1

In [ ]:
outdata_1 = df[ df['Fare'] < (q1-IQR*1.5)]
outdata_2 = df[ df['Fare'] > (q3+IQR*1.5)]

len(outdata_1), len(outdata_2)

In [ ]:
print( sum(outdata_1['Gender'] == 'female') + sum(outdata_2['Gender'] == 'female'))

T1-2. 주어진 데이터에서 이상치(소수점 나이)를 찾고 올림, 내림, 버림(절사)했을때 3가지 모두 이상치 'age' 평균을 구한 다음 모두 더하여 출력하시오

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/basic1.csv')

In [ ]:
df.head()

In [ ]:
# 소수점 나이 추출/ 올림,내림,버림을 각각 적용했을 때의 평균 구하기/ 3가지 경우의 평균 모두 합

In [ ]:
df = df[ (df['age'] - np.floor(df['age'])) != 0 ] # 원본 age값 - 내림 age값의 계산 결과가 0이 아닌 경우 True 반환
df

In [ ]:
# 올림,내림,버림의 각 평균값
ceil_mean = np.ceil(df['age']).mean()
floor_mean = np.floor(df['age']).mean()
trunc_mean = np.trunc(df['age']).mean()

In [ ]:
print(ceil_mean + floor_mean + trunc_mean)

T1-3. 주어진 데이터에서 결측치가 80%이상 되는 컬럼은(변수는) 삭제하고, 80% 미만인 결측치가 있는 컬럼은 'city'별 중앙값으로 값을 대체하고 'f1'컬럼의 평균값을 출력하세요!

In [ ]:
# 결측치 처리(map 활용)
import pandas as pd
import numpy as np

df = pd.read_csv('/content/basic1.csv')
print(df.shape)
print(df.isna().sum())
df.head()

(100, 8)
id       0
age      0
city     0
f1      31
f2       0
f3      95
f4       0
f5       0
dtype: int64

     id   age city    f1  f2   f3    f4         f5
0  id01   2.0   서울   NaN   0  NaN  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  NaN  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  NaN  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  NaN  INFP  52.667078
4  id05  24.0   서울  85.0   2  NaN  ISFJ  29.269869

In [ ]:
df.isna().sum() / df.shape[0] # 결측치 비율: 결측치 수 / 전체 수
# df.shape[0]:전체 행의 수 반환  df.shape[1]:열

id      0.00
age     0.00
city    0.00
f1      0.31
f2      0.00
f3      0.95
f4      0.00
f5      0.00
dtype: float64

In [ ]:
df = df.drop(columns=['f3'])
df

       id    age city    f1  f2    f4         f5
0    id01    2.0   서울   NaN   0  ENFJ  91.297791
1    id02    9.0   서울  70.0   1  ENFJ  60.339826
2    id03   27.0   서울  61.0   1  ISTJ  17.252986
3    id04   75.0   서울   NaN   2  INFP  52.667078
4    id05   24.0   서울  85.0   2  ISFJ  29.269869
..    ...    ...  ...   ...  ..   ...        ...
95   id96   92.0   경기  53.0   1  ENTJ  52.667078
96   id97  100.0   경기   NaN   0  INFP  67.886373
97   id98   39.0   경기  58.0   2  INFP  98.429899
98   id99    1.0   경기  47.0   0  ESFJ  97.381034
99  id100   47.0   경기  53.0   0  ESFP  33.308999

[100 rows x 7 columns]

In [ ]:
df['city'].value_counts()

city
경기    41
서울    20
대구    20
부산    19
Name: count, dtype: int64

In [ ]:
k_median = df[df['city'] == '경기']['f1'].median() # 'city'열의 값이 '경기'인 행을 필터링하고, 그중에서 'f1'열의 중앙값을 계산
s_median = df[df['city'] == '서울']['f1'].median()
d_median = df[df['city'] == '대구']['f1'].median()
b_median = df[df['city'] == '부산']['f1'].median()

k_median, s_median, d_median, b_median

(58.0, 68.0, 75.0, 62.0)

In [ ]:
df.head()

     id   age city    f1  f2    f4         f5
0  id01   2.0   서울   NaN   0  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  INFP  52.667078
4  id05  24.0   서울  85.0   2  ISFJ  29.269869

In [ ]:
df['f1'] = df['f1'].fillna(df['city'].map({'경기':k_median, '서울':s_median, '대구':d_median, '부산':b_median}))
# map(): pandas에서 시리즈(Series)의 값들을 다른 값으로 매핑(mapping)하거나 변환
# df의 한 열은 시리즈 객체다.  df은 여러개의 시리즈가 같은 인덱스를 기준으로 모여 있는 2차원 구조

# 만약 f1 중앙값으로 대체한다면
# df['f1'] = df['f1'].fillna(df['f1'].median())

In [ ]:
df.head()

     id   age city    f1  f2    f4         f5
0  id01   2.0   서울  68.0   0  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  ISTJ  17.252986
3  id04  75.0   서울  68.0   2  INFP  52.667078
4  id05  24.0   서울  85.0   2  ISFJ  29.269869

In [ ]:
print(df['f1'].mean())

65.52

T1-4. 주어진 데이터 중 train.csv에서 'SalePrice'컬럼의 왜도와 첨도를 구한 값과, 'SalePrice'컬럼을 스케일링(log1p)로 변환한 이후 왜도와 첨도를 구해 모두 더한 다음 소수점 2째자리까지 출력하시오

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('')
df['SalePrice'].head()

In [ ]:
sale_skew1 = df['SalePrice'].skew() # 왜도 계산
slae_kurt1 = df['SalePrice'].kurt() # 첨도 계산

In [ ]:
df['SalePrice'] = np.log1p(df['SalePrice']) # 로그변환

In [ ]:
sale_skew2 = df['SalePrice'].skew()
sale_kurt2 = df['SalePrice'].kurt()

In [ ]:
print(round(sale_skew1 + sale_skew2 + sale_kurt1 + sale_krut2, 2))

T1-5. 주어진 데이터 중 basic1.csv에서 'f4'컬럼 값이 'ENFJ'와 'INFP'인 'f1'의 표준편차 차이를 절대값으로 구하시오

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/basic1.csv')
df.head()

     id   age city    f1  f2   f3    f4         f5
0  id01   2.0   서울   NaN   0  NaN  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  NaN  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  NaN  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  NaN  INFP  52.667078
4  id05  24.0   서울  85.0   2  NaN  ISFJ  29.269869

In [ ]:
enfj_std = df.groupby('f4')['f1'].std()['ENFJ']
infp_std = df.groupby('f4')['f1'].std()['INFP']
enfj_std, infp_std

(np.float64(17.727097901235837), np.float64(23.58671942711265))

In [ ]:
print(abs(enfj_std - infp_std))

5.859621525876815

T1-6. 주어진 데이터 중 basic1.csv에서 'f1'컬럼 결측 데이터를 제거하고, 'city'와 'f2'을 기준으로 묶어 합계를 구하고, 'city가 경기이면서 f2가 0'인 조건에 만족하는 f1 값을 구하시오

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/basic1.csv')
df.isna().sum()

id       0
age      0
city     0
f1      31
f2       0
f3      95
f4       0
f5       0
dtype: int64

In [ ]:
df = df.dropna(subset=['f1'])

In [ ]:
df.head()

     id   age city    f1  f2   f3    f4         f5
1  id02   9.0   서울  70.0   1  NaN  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  NaN  ISTJ  17.252986
4  id05  24.0   서울  85.0   2  NaN  ISFJ  29.269869
5  id06  22.0   서울  57.0   0  vip  INTP  20.129444
6  id07  36.3   서울  60.0   1  NaN  ISFJ   9.796378

In [ ]:
df2 = df.groupby(['city','f2']).sum()
df2

                                                        id    age     f1   f3  \
city f2
경기   0   id69id72id74id75id76id77id80id84id85id88id91id...  720.4  833.0  vip
     1            id63id67id70id78id81id83id89id92id95id96  696.0  670.0  vip
     2                                id61id64id68id71id98  239.0  311.0    0
대구   0                        id40id41id43id45id49id53id57  387.0  527.0    0
     1                                        id47id50id52  217.6  235.0    0
     2                                        id42id55id58  140.0  211.0    0
부산   0                            id24id27id31id32id33id39  331.0  389.0  vip
     1                                id22id23id26id28id36  188.7  315.0    0
     2                                                id29  -13.5   47.0    0
서울   0                                    id06id11id13id16  145.0  278.0  vip
     1                    id02id03id07id08id10id14id15id20  315.3  534.0    0
     2                                        id05id09id18   68.3  207.0    0

                                                        f4          f5
city f2
경기   0   ESTJESTJESTPESTPENTJINFPISFPINTPINFJESTJINTPIS...  943.944823
     1            ISFJISFJISTPINTJISFJENTPENTJINFPINTJENTJ  657.241212
     2                                INTPESFPISFPISFPINFP  362.300060
대구   0                        ENFPENFJISTPENFJINTPESTPISFJ  183.199568
     1                                        ESTJENFPISFJ  241.333824
     2                                        ESTPENTPESTP   79.667919
부산   0                            INFJESTPESFJISFJENFJINFJ  284.371097
     1                                ENFPISTPENFPENTPINTP  299.270973
     2                                                ENTP   67.886373
서울   0                                    INTPENFPESFJESFP  218.528577
     1                    ENFJISTJISFJINFJISFPENTJENTPINTJ  438.485010
     2                                        ISFJESFJISFJ  126.661135

In [ ]:
print(df2.iloc[0]['f1']) # 조건에 맞는 값 출력 ('city가 경기이면서 f2가 0'인 조건에 만족하는 f1 값)

833.0

T1-7. 'f4'컬럼의 값이 'ESFJ'인 데이터를 'ISFJ'로 대체하고, 'city'가 '경기'이면서 'f4'가 'ISFJ'인 데이터 중 'age'컬럼의 최대값을 출력하시오

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/basic1.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      100 non-null    object
 1   age     100 non-null    float64
 2   city    100 non-null    object
 3   f1      69 non-null     float64
 4   f2      100 non-null    int64
 5   f3      5 non-null      object
 6   f4      100 non-null    object
 7   f5      100 non-null    float64
dtypes: float64(3), int64(1), object(4)
memory usage: 6.4+ KB

     id   age city    f1  f2   f3    f4         f5
0  id01   2.0   서울   NaN   0  NaN  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  NaN  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  NaN  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  NaN  INFP  52.667078
4  id05  24.0   서울  85.0   2  NaN  ISFJ  29.269869

In [ ]:
df[df['f4'] == 'ESFJ'] # ESFJ 값 가진 데이터 확인

      id   age city    f1  f2   f3    f4         f5
8   id09   3.3   서울  35.0   2  NaN  ESFJ  17.252986
12  id13  15.0   서울  68.0   0  NaN  ESFJ  83.685380
30  id31  86.0   부산  77.0   0  NaN  ESFJ  73.586397
58  id59  64.0   대구   NaN   1  NaN  ESFJ  20.129444
98  id99   1.0   경기  47.0   0  NaN  ESFJ  97.381034

In [ ]:
df['f4'] = df['f4'].replace({'ESFJ':'ISFJ'})

In [ ]:
df[df['f4'] == 'ESFJ']

Empty DataFrame
Columns: [id, age, city, f1, f2, f3, f4, f5]
Index: []

In [ ]:
df[ (df['city'] == '경기') & (df['f4'] == 'ISFJ') ] # df으로 필터링 할 때는 and 대신 & 사용

      id   age city    f1  f2   f3    f4         f5
62  id63  88.0   경기  86.0   1  NaN  ISFJ  73.586397
66  id67  66.0   경기  52.0   1  NaN  ISFJ  73.586397
72  id73  90.0   경기   NaN   1  NaN  ISFJ  73.586397
80  id81  86.0   경기  50.0   1  NaN  ISFJ  37.113739
98  id99   1.0   경기  47.0   0  NaN  ISFJ  97.381034

In [ ]:
df[ (df['city'] == '경기') & (df['f4'] == 'ISFJ') ]['age'].max() # df['컬럼'].mean()

90.0